import a from"node:fs";import f from"node:path";import{okfVersion as D}from"../adoption.js";import{comparePaths as E,Doc as x,filesUnder as R,hasMarkdownUnder as j,isDirectory as v,markdownUnder as F,parseFrontmatter as S,RESERVED as k}from"../bundle.js";const U=/^<.*>$/,h="raw",C="Record",T="cited by no concept";function g(e){const n=String(e.meta.description??"").trim();return n&&!U.test(n)?n:e.type||""}function V(e){const n=new Set(F(e.root).map(o=>f.dirname(o))),r=f.join(e.root,h);v(r)&&n.add(r);const s=[];for(const o of[...n].sort(E)){const c=f.relative(e.root,o).split(f.sep).join("/"),t=c==="."?"":c;t==="inbox"||t.startsWith("inbox/")||t.startsWith(`${h}/`)||t==="conventions/templates"||t.startsWith("conventions/templates/")||s.push(o)}return s}function W(e,n){const r=[],s=[];for(const c of R(n)){const t=f.relative(n,c).split(f.sep).join("/");if(t!=="index.md"){if(t.endsWith(".md")){const{meta:p}=S(a.readFileSync(c,"utf8"));if(p.type===C){r.push([t,g(new x({path:c,rel:t,text:"",meta:p}))]);continue}}s.push([t,N(e,t)])}}const o=[];for(const[c,t]of[["Records",r],["Files",s]])if(o.length&&o.push(""),o.push(`# ${c}`),!!t.length){o.push("");for(const[p,m]of[...t].sort(w))o.push(`* [${p}](${p})`+(m?` - ${m}`:""))}return o.join(`
`).replace(/\s+$/,"")+`
`}function N(e,n){const r=`/${h}/${n}`;for(const s of e.concepts){const o=s.sources.find(t=>t.resource===r);if(!o)continue;return String(o.title??"").trim()||String(s.meta.description??"").trim()}return T}function O(e,n){const r=f.relative(e.root,n);if(r===h)return W(e,n);const s=new Map,o=[],c=a.readdirSync(n,{withFileTypes:!0}).sort((i,u)=>i.name===u.name?0:i.name<u.name?-1:1);for(const i of c){const u=f.join(n,i.name);if(i.isDirectory()){if(r===""&&i.name==="inbox")continue;j(u)&&o.push(i.name);continue}if(f.extname(i.name)!==".md"||k.has(i.name))continue;const{meta:l}=S(a.readFileSync(u,"utf8")),d=new x({path:u,rel:f.relative(e.root,u),text:"",meta:l}),$=d.type||"Untyped",y=s.get($)??[];y.push([i.name,g(d)]),s.set($,y)}const t=[];if(o.length){t.push("# Subdirectories"),t.push("");for(const i of o)t.push(`* [${i}/](${i}/)`);t.push("")}for(const i of[...s.keys()].sort()){t.push(`# ${i}`),t.push("");const u=s.get(i);for(const[l,d]of[...u].sort(w))t.push(`* [${l}](${l})`+(d?` - ${d}`:""));t.push("")}const m=(t.length?t:["# Concepts",""]).join(`
`).replace(/\s+$/,"")+`
`;return r===""||r==="."?`---
okf_version: "${D()}"
---

`+m:m}function w(e,n){return e[0]!==n[0]?e[0]<n[0]?-1:1:e[1]!==n[1]?e[1]<n[1]?-1:1:0}function b(e,n){const r=f.join(n,"index.md"),s=O(e,n);return(a.existsSync(r)?a.readFileSync(r,"utf8"):null)===s?!1:(a.writeFileSync(r,s,"utf8"),!0)}export{h as STORE,V as directoriesNeedingIndex,O as render,b as write};
