import c from"node:path";import{gate as w}from"./adoption.js";import{Bundle as f,BundleError as g,comparePaths as k,findRoot as b}from"./bundle.js";import*as E from"./checks/conformance.js";import*as l from"./checks/hashes.js";import*as j from"./checks/inbox.js";import*as S from"./checks/index-diff.js";import*as $ from"./checks/links.js";import{ERROR as v,render as O}from"./finding.js";import*as u from"./generate/index-file.js";import{initBundle as R}from"./init.js";const p=0,y=1,d=2,m={conformance:E.run,links:$.run,hashes:l.run,index:S.run,inbox:j.run},h=`usage: vwiki <command> [<args>]

commands:
  init [<dir>]                          copy the bundle skeleton into <dir> (default: .wiki)
  validate [<bundle>] [--fix] [--json]  report rule violations

options:
  --fix     repin hashes and regenerate indexes before checking
  --json    print findings as JSON
  -h, --help

exit codes: 0 nothing to report, 1 the bundle breaks a rule, 2 the tool could not run`;class s extends Error{}function A(n){return f.load(b(n||process.cwd()))}const x=10;function N(n){const o=new Set(l.repin(n));let t=f.load(n.root),i=!1;for(let r=0;r<x;r+=1){let e=!1;for(const a of u.directoriesNeedingIndex(t))u.write(t,a)&&(o.add(c.join(a,"index.md")),e=!0);if(t=f.load(t.root),!e){i=!0;break}}if(!i)throw new Error(`index generation did not converge in ${x} passes; an index that changes another index that changes it back is the usual cause`);if(o.size){for(const r of l.repin(t))o.add(r);t=f.load(t.root)}return{bundle:t,written:[...o].sort(k)}}function B(n,o){let t=A(n.path);const i=[...w(t)];if(n.fix){const e=N(t);t=e.bundle;for(const a of e.written)o.out(c.relative(t.root,a).split(c.sep).join("/"))}for(const e of Object.keys(m))i.push(...m[e](t));const r=O(i,n.json);return r&&o.out(r),i.some(e=>e.level===v)?y:p}function F(n){if(!n.length)throw new s("a command is required");if(n[0]==="-h"||n[0]==="--help")return{cmd:"help",path:null,fix:!1,json:!1};const o=n[0];if(o!=="init"&&o!=="validate")throw new s(`unknown command: ${o}`);let t=null,i=!1,r=!1;for(const e of n.slice(1)){if(e==="-h"||e==="--help")return{cmd:"help",path:null,fix:!1,json:!1};if(e==="--fix"||e==="--json"){if(o!=="validate")throw new s(`${o} takes no ${e}`);e==="--fix"?i=!0:r=!0;continue}if(e.startsWith("-")&&e!=="-")throw new s(`unknown option: ${e}`);if(t!==null)throw new s(`unexpected argument: ${e}`);t=e}return{cmd:o,path:t,fix:i,json:r}}function P(n=[],o={}){const t=o.out??(e=>console.log(e)),i=o.err??(e=>console.error(e));let r;try{r=F(n)}catch(e){return i(h),i(`vwiki: ${e instanceof Error?e.message:String(e)}`),d}try{return r.cmd==="help"?(t(h),p):r.cmd==="init"?R(r.path,{out:t}):B(r,{out:t})}catch(e){return e instanceof g?(i(`vwiki: ${e.message}`),d):(i(e instanceof Error&&e.stack?e.stack:String(e)),d)}}export{m as CHECKS,y as FINDINGS,x as MAX_PASSES,p as OK,d as TOOL_ERROR,h as USAGE,N as applyFix,P as main,F as parseArgs};
